/** Profile / account endpoints — ported from views/profile/profile.js. */
import { apiFetch } from '$lib/api/client';
import { getCsrfHeaders } from '$lib/api/csrf';
import type { User } from '$lib/api/types';
import { t } from '$lib/i18n/index.svelte';

const JSON_HEADERS = { 'Content-Type': 'application/json' };

export interface ProfilePatch {
	username?: string;
	given_name?: string;
	family_name?: string;
	preferred_locale?: string;
	notify_on_share?: boolean;
}

export async function updateProfile(patch: ProfilePatch): Promise<User> {
	const res = await apiFetch('/api/auth/me/profile', {
		method: 'PATCH',
		credentials: 'same-origin',
		headers: { ...JSON_HEADERS, ...getCsrfHeaders() },
		body: JSON.stringify(patch)
	});
	if (!res.ok) {
		const err = (await res.json().catch(() => ({}))) as { message?: string; error?: string };
		// 409 covers two distinct conflicts that share the same status. The
		// server's audit log carries the structured `reason`; the JSON body
		// only exposes a human-readable message, so we branch on that.
		if (res.status === 409) {
			const msg = (err.message || err.error || '').toLowerCase();
			const key = msg.includes('already claimed')
				? 'profile.username_immutable_error'
				: 'profile.username_taken_error';
			const fallback = msg.includes('already claimed')
				? "Your username has already been set and can't be changed."
				: 'That username is already taken.';
			throw new Error(t(key, fallback));
		}
		// 403 here means the field is governed by the identity provider.
		if (res.status === 403) {
			throw new Error(
				t(
					'profile.edit_oidc_managed',
					'Your profile is managed by your identity provider. Update it there; changes appear on your next sign-in.'
				)
			);
		}
		throw new Error(err.message || err.error || `profile update failed: ${res.status}`);
	}
	return (await res.json()) as User;
}

export async function changePassword(currentPw: string, newPw: string): Promise<void> {
	const res = await apiFetch('/api/auth/change-password', {
		method: 'PUT',
		credentials: 'same-origin',
		headers: { ...JSON_HEADERS, ...getCsrfHeaders() },
		body: JSON.stringify({ current_password: currentPw, new_password: newPw })
	});
	if (!res.ok) throw new Error(`password change failed: ${res.status}`);
}

export async function updateAvatar(image: string | null): Promise<void> {
	const res = await apiFetch('/api/auth/me/image', {
		method: 'PUT',
		credentials: 'same-origin',
		headers: { ...JSON_HEADERS, ...getCsrfHeaders() },
		body: JSON.stringify({ image })
	});
	if (!res.ok) throw new Error(`avatar update failed: ${res.status}`);
}

export interface AppPassword {
	id: string;
	label: string;
	active?: boolean;
	created_at: string;
	last_used_at?: string;
}

/**
 * Labels the server uses for sessions auto-generated when a Nextcloud-style
 * client authenticates (vs. user-created app passwords). Ported from
 * `views/profile/profile.js`'s `AUTO_LABELS`.
 */
const AUTO_LABELS = ['Nextcloud', 'Nextcloud (OIDC)'];

/** True when an app password was auto-generated by a client session login. */
export function isAutoAppPassword(pw: Pick<AppPassword, 'label'>): boolean {
	return AUTO_LABELS.includes(pw.label);
}

export async function listAppPasswords(): Promise<AppPassword[]> {
	const res = await apiFetch('/api/auth/app-passwords', { credentials: 'same-origin' });
	if (!res.ok) return [];
	const data = (await res.json()) as AppPassword[] | { app_passwords?: AppPassword[] };
	return Array.isArray(data) ? data : (data.app_passwords ?? []);
}

/** Returns the one-time generated password (shown once). */
export async function createAppPassword(label: string): Promise<string> {
	const res = await apiFetch('/api/auth/app-passwords', {
		method: 'POST',
		credentials: 'same-origin',
		headers: { ...JSON_HEADERS, ...getCsrfHeaders() },
		body: JSON.stringify({ label })
	});
	if (!res.ok) {
		const e = (await res.json().catch(() => ({}))) as { error?: string; message?: string };
		throw new Error(e.error || e.message || `create app password failed: ${res.status}`);
	}
	const data = (await res.json()) as { password: string };
	return data.password;
}

export async function revokeAppPassword(id: string): Promise<void> {
	const res = await apiFetch(`/api/auth/app-passwords/${encodeURIComponent(id)}`, {
		method: 'DELETE',
		credentials: 'same-origin',
		headers: getCsrfHeaders()
	});
	if (!res.ok) throw new Error(`revoke app password failed: ${res.status}`);
}
